class CountryData {
  static final List<String> countries = [
    'AU',
    'CA',
    'DE',
    'ES',
    'FR',
    'IT',
    'JP',
    'LB',
    'UK',
    'US',
  ];

  static final Map<String, List<String>> citiesByCountry = {
    'AU': [
      'Adelaide',
      'Brisbane',
      'Canberra',
      'Gold Coast',
      'Hobart',
      'Melbourne',
      'Newcastle',
      'Perth',
      'Sydney',
      'Wollongong',
    ],
    'CA': [
      'Calgary',
      'Edmonton',
      'Hamilton',
      'London',
      'Montreal',
      'Ottawa',
      'Quebec City',
      'Toronto',
      'Vancouver',
      'Winnipeg',
    ],
    'DE': [
      'Berlin',
      'Cologne',
      'Dortmund',
      'Düsseldorf',
      'Essen',
      'Frankfurt',
      'Hamburg',
      'Leipzig',
      'Munich',
      'Stuttgart',
    ],
    'ES': [
      'Bilbao',
      'Las Palmas',
      'Málaga',
      'Murcia',
      'Palma',
      'Seville',
      'Valencia',
      'Zaragoza',
      'Barcelona',
      'Madrid',
    ],
    'FR': [
      'Bordeaux',
      'Lille',
      'Lyon',
      'Marseille',
      'Nantes',
      'Nice',
      'Paris',
      'Rennes',
      'Strasbourg',
    ],
    'IT': [
      'Bologna',
      'Florence',
      'Genoa',
      'Milan',
      'Naples',
      'Palermo',
      'Rome',
      'Turin',
      'Venice',
      'Verona',
    ],
    'JP': [
      'Fukuoka',
      'Kawasaki',
      'Kobe',
      'Kyoto',
      'Nagoya',
      'Osaka',
      'Saitama',
      'Sapporo',
      'Tokyo',
      'Yokohama',
    ],
    'LB': [
      'Aley',
      'Baabda',
      'Baalbek',
      'Batroun',
      'Beirut',
      'Bint Jbeil',
      'Byblos',
      'Chouf',
      'Hasbaya',
      'Hermel',
      'Jbeil',
      'Jounieh',
      'Marjayoun',
      'Rashaya',
      'Saida',
      'Sour',
      'Taanayel',
      'Tripoli',
      'Tyre',
      'Zahle',
      'Zgharta',
    ],
    'UK': [
      'Birmingham',
      'Bristol',
      'Glasgow',
      'Leeds',
      'Liverpool',
      'London',
      'Manchester',
      'Newcastle',
      'Nottingham',
      'Sheffield',
    ],
    'US': [
      'Chicago',
      'Dallas',
      'Houston',
      'Los Angeles',
      'Miami',
      'New York',
      'Philadelphia',
      'Phoenix',
      'San Antonio',
      'San Diego',
    ],
  };
}
