class CountryData {
  static final List<String> countries = [
    'US',
    'CA',
    'LB',
    'FR',
    'DE',
    'UK',
    'AU',
    'IT',
    'ES',
    'JP',
  ];

  static final Map<String, List<String>> citiesByCountry = {
    'US': [
      'New York',
      'Los Angeles',
      'Chicago',
      'Houston',
      'Miami',
      'Phoenix',
      'Philadelphia',
      'San Antonio',
      'San Diego',
      'Dallas'
    ],
    'CA': [
      'Toronto',
      'Vancouver',
      'Montreal',
      'Calgary',
      'Ottawa',
      'Edmonton',
      'Winnipeg',
      'Quebec City',
      'Hamilton',
      'London'
    ],
    'LB': [
      'Beirut',
      'Tripoli',
      'Sidon',
      'Tyre',
      'Zahle',
      'Jounieh',
      'Batroun',
      'Byblos',
      'Nabatieh',
      'Baalbek',
      'Jbeil',
      'Bekaa Valley',
      'Zahlé',
      'Jounieh',
      'Bint Jbeil',
      'Chouf',
      'Marjayoun',
      'Aley',
      'Rashaya',
      'Saida',
      'Zahle',
      'Baalbek',
      'Taanayel',
      'Riyak',
      'Jiyeh',
      'Sour',
      'Ehdin',
      'Hermel',
      'Saghbine',
      'Hasbaya',
      'Bhamdoun',
      'Mazraat Yachouh',
      'Ras el-Matn',
      'Broummana',
      'Aley',
      'Bteghrine',
      'Hosh Hala',
      'Deir el Qamar',
      'Zgharta',
      'Kousba',
      'Miziara',
      'Qoubaiyat',
      'Bechare',
      'Mansoura',
      'Babda',
      'Naccache',
      'Sin el Fil',
      'Horsh Tabet',
      'Baabda',
      'Fanar',
    ],
    'FR': [
      'Paris',
      'Marseille',
      'Lyon',
      'Toulouse',
      'Nice',
      'Nantes',
      'Strasbourg',
      'Bordeaux',
      'Lille',
      'Rennes'
    ],
    'DE': [
      'Berlin',
      'Hamburg',
      'Munich',
      'Cologne',
      'Frankfurt',
      'Stuttgart',
      'Düsseldorf',
      'Dortmund',
      'Essen',
      'Leipzig'
    ],
    'UK': [
      'London',
      'Manchester',
      'Birmingham',
      'Glasgow',
      'Liverpool',
      'Newcastle',
      'Sheffield',
      'Leeds',
      'Bristol',
      'Nottingham'
    ],
    'AU': [
      'Sydney',
      'Melbourne',
      'Brisbane',
      'Perth',
      'Adelaide',
      'Gold Coast',
      'Canberra',
      'Newcastle',
      'Wollongong',
      'Hobart'
    ],
    'IT': [
      'Rome',
      'Milan',
      'Naples',
      'Turin',
      'Palermo',
      'Genoa',
      'Bologna',
      'Florence',
      'Venice',
      'Verona'
    ],
    'ES': [
      'Madrid',
      'Barcelona',
      'Valencia',
      'Seville',
      'Zaragoza',
      'Málaga',
      'Murcia',
      'Palma',
      'Las Palmas',
      'Bilbao'
    ],
    'JP': [
      'Tokyo',
      'Yokohama',
      'Osaka',
      'Nagoya',
      'Sapporo',
      'Fukuoka',
      'Kawasaki',
      'Kobe',
      'Kyoto',
      'Saitama'
    ],
  };
}
